### ISSUE TITLE
Customer Maintenance JSON Layout

### ISSUE THREAD

**Issue by radu2501** [consultingwerk/SmartComponentsAngularDemo#7]
@mikefechner, In the Customer Maintenance screen JSON layout, the customer viewer is getting a `customerGrid` object name. Shouldn't it be `customerViewer`?

**Comment by mikefechner** [comment]
Fixed this. Generally, for issues that are caused by the backend, please log tickets on JIRA.

**Comment by radu2501** [comment]
>Generally, for issues that are caused by the backend, please log tickets on JIRA.

Will do. However, it is still not fixed (on my backend at least - 116_64).

**Comment by BuildserverConsultingwerk** [comment]
Sure it is not….

Von: Radu Nicoara [mailto:notifications@github.com]
Gesendet: Dienstag, 27. Februar 2018 08:52
An: consultingwerk/SmartComponentsAngularDemo <SmartComponentsAngularDemo@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [consultingwerk/SmartComponentsAngularDemo] Customer Maintenance JSON Layout (#7)


Generally, for issues that are caused by the backend, please log tickets on JIRA.

Will do. However, it is still not fixed (on my backend at least - 116_64).

**Comment by mikefechner** [comment]
It's not relevant enough to justify me spending time on that now. It does not cause any issue. Or?

**Comment by radu2501** [comment]
> It does not cause any issue. Or?

It does not, just that the demo app references the customerGrid instead of viewer for setting up input change listeners. Not that big of an issue.

>Fixed this.

I must have misunderstood the above statement, that is why I mentioned that it is still not fixed :-)
